name = "gcc"
version = "15.1.1"
description = "GNU Compiler Collection"
licenses = ["GPL-2.0","LGPL-2.1","GCC RUNTIME LIBRARY EXCEPTION"]
repository = "https://github.com/gcc-mirror/gcc"

branch="releases/gcc-15"