name = "coreutils"
version = "0.0.29"
description = "Cross-platform Rust rewrite of the GNU coreutils - RunixOS fork"
licenses = ["MIT"]
repository = "https://github.com/renhiyama/coreutils"
branch = "runixos"
local_path = "../../../coreutils"
dependencies = ["rust"]
