name = "rust-native"
version = "1.93.0"
description = "Rust toolchain (rustc + cargo) built to RUN on RunixOS (self-hosting)"
licenses = ["MIT OR Apache-2.0"]
repository = "https://github.com/renhiyama/rust"
branch = "master"
local_path = "../../../rust"
dependencies = ["llvm", "glibc", "llvm-runtimes", "zlib", "llvm21", "python"]
