name = "nushell"
version = "0.105.1"
description = "A new type of shell - RunixOS fork"
licenses = ["MIT"]
repository = "https://github.com/renhiyama/nushell"
branch = "runixos"
local_path = "../../../nushell"
dependencies = ["rust"]
