name = "fastfetch"
version = "2.64.2"
description = "Fast system information tool, with a RunixOS-branded logo"
licenses = ["MIT"]
repository = "https://github.com/renhiyama/fastfetch"
branch = "runixos"
local_path = "../../../fastfetch"
dependencies = ["glibc"]
